"""
A module to represent various constants used in the application.
"""

AUXKNOW_OPTIMIZATION_CONSTANT = 4
DEFAULT_ANSWER_LENGTH_PARAGRAPHS: int = 3
DEFAULT_LINES_PER_PARAGRAPH: int = 5
MAX_ANSWER_LENGTH_PARAGRAPHS: int = 8
MAX_LINES_PER_PARAGRAPH: int = 10
DEFAULT_PERPLEXITY_MODEL: str = "sonar-pro"
MAX_CONTEXT_TOKENS: int = 4096
DEFAULT_AUTO_PROMPT_AUGMENT = True
DEFAULT_PROMPT_AUGMENTATION_MODEL = "gpt-4o-mini"
PROMPT_AUGMENTATION_FACTOR = 0.22
DEFAULT_PROMPT_AUGMENTATION_TEMPERATURE = (
    AUXKNOW_OPTIMIZATION_CONSTANT * PROMPT_AUGMENTATION_FACTOR
)
DEFAULT_ENABLE_UNBIASED_REASONING = True
DEFAULT_AUXKNOW_SEARCH_VERBOSE = False
